FROM node:18-alpine

WORKDIR /app

# Pass build-time environment variables
ARG API_URL
ARG NEXT_PUBLIC_ADMIN_SEQUENCE
ARG JWT_SECRET

# Set them as ENV so Next.js can use them
ENV API_URL=$API_URL
ENV NEXT_PUBLIC_ADMIN_SEQUENCE=$NEXT_PUBLIC_ADMIN_SEQUENCE
ENV JWT_SECRET=$JWT_SECRET

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

RUN npm run build

CMD [ "npm", "run", "start" ]